#!/usr/bin/env python3
"""Deterministic LookML generator from Phase 1 inventory.

Reads phase1/inventory/*.json and writes phase2/lookml/{models,views}/*.lkml
plus OBJECT_MAPPING.{json,md}.

Standards applied from looker-open-source/looker-skills:
- primary_key on every view
- explicit join relationship
- descriptions on explores / measures
- granular includes in the model file
"""
from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path

from lib.dax_patterns import classify_dax, extract_table_column
from lib.mapping import (
    OBJECT_EQUIVALENCE,
    cardinality_to_relationship,
    guess_primary_key,
    is_internal_table,
    lookml_field_type,
)
from lib.naming import (
    lookml_field_name,
    lookml_view_name,
    quote_sql_ident,
    snake_case,
    sql_table_placeholder,
)

ROOT = Path(__file__).resolve().parent
PHASE1_INV = ROOT.parent / "phase1" / "inventory"
LOOKML_ROOT = ROOT / "lookml"
VIEWS_DIR = LOOKML_ROOT / "views"
MODELS_DIR = LOOKML_ROOT / "models"


def load_inventory(inv_dir: Path | None = None) -> dict:
    inv = inv_dir or PHASE1_INV
    def j(name: str):
        p = inv / name
        if not p.exists():
            raise FileNotFoundError(f"Missing Phase 1 inventory: {p}")
        return json.loads(p.read_text())

    return {
        "a1": j("01_tables_columns.json"),
        "a2": j("02_dax_objects.json"),
        "a3": j("03_relationships.json"),
        "a4": j("04_power_query_m.json"),
        "a5": j("05_tmschema_extras.json"),
        "counts": j("OBJECT_COUNTS.json") if (inv / "OBJECT_COUNTS.json").exists() else {},
    }


def business_tables(a1: dict) -> list[dict]:
    out = []
    for t in a1.get("tables") or []:
        name = t.get("table_name") or ""
        if is_internal_table(name):
            continue
        if t.get("is_business") or not t.get("is_internal"):
            if is_internal_table(name):
                continue
            out.append(t)
    # de-dupe
    seen = set()
    uniq = []
    for t in out:
        n = t["table_name"]
        if n in seen:
            continue
        seen.add(n)
        uniq.append(t)
    return uniq


def columns_by_table(a1: dict) -> dict[str, list[dict]]:
    m: dict[str, list[dict]] = defaultdict(list)
    for c in a1.get("columns") or []:
        m[c["table_name"]].append(c)
    return m


def calc_cols_by_table(a2: dict) -> dict[str, list[dict]]:
    m: dict[str, list[dict]] = defaultdict(list)
    for c in a2.get("calculated_columns") or []:
        tbl = c.get("table") or c.get("table_name")
        if tbl and not is_internal_table(tbl):
            m[tbl].append(c)
    return m


def escape_lookml_string(s: str) -> str:
    return (s or "").replace("\\", "\\\\").replace('"', '\\"')


def render_view(
    table: dict,
    columns: list[dict],
    calc_cols: list[dict],
    measures_for_view: list[dict],
    field_name_map: dict[tuple[str, str], str],
) -> str:
    tname = table["table_name"]
    vname = lookml_view_name(tname)
    pk_col = guess_primary_key(columns)
    lines: list[str] = []
    lines.append("# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory")
    lines.append(f"# Source Power BI table: {tname}")
    if table.get("is_calculated_table") or table.get("table_type") == "calculated_table":
        lines.append("# Calculated table — prefer warehouse materialization; sql_table_name is a placeholder.")
    lines.append(f"view: {vname} {{")
    lines.append(f'  label: "{escape_lookml_string(tname)}"')
    lines.append(f'  sql_table_name: {sql_table_placeholder(vname)} ;;')
    lines.append("")

    used_fields: set[str] = set()

    def emit_dimension(col_name: str, data_type, pandas_dtype, *, primary: bool = False, description: str | None = None, hidden: bool = False):
        fname = lookml_field_name(col_name)
        # uniquify within view
        base = fname
        i = 2
        while fname in used_fields:
            fname = f"{base}_{i}"
            i += 1
        used_fields.add(fname)
        field_name_map[(tname, col_name)] = fname
        ftype = lookml_field_type(data_type, pandas_dtype)
        sql_col = quote_sql_ident(col_name)
        if ftype == "time":
            lines.append(f"  dimension_group: {fname} {{")
            lines.append(f'    label: "{escape_lookml_string(col_name)}"')
            if description:
                lines.append(f'    description: "{escape_lookml_string(description)}"')
            lines.append("    type: time")
            lines.append("    timeframes: [raw, date, week, month, quarter, year]")
            lines.append(f"    sql: ${{TABLE}}.{sql_col} ;;")
            if primary:
                lines.append("    # NOTE: time primary keys are unusual; prefer a date_raw key if needed")
            if hidden:
                lines.append("    hidden: yes")
            lines.append("  }")
            lines.append("")
            # also expose raw-friendly dimension name for joins if needed
            if primary:
                lines.append(f"  dimension: {fname}_key {{")
                lines.append("    primary_key: yes")
                lines.append(f'    label: "{escape_lookml_string(col_name)} Key"')
                lines.append("    type: date")
                lines.append(f"    sql: ${{TABLE}}.{sql_col} ;;")
                lines.append("    hidden: yes")
                lines.append("  }")
                lines.append("")
                field_name_map[(tname, col_name)] = f"{fname}_key"
        else:
            lines.append(f"  dimension: {fname} {{")
            if primary:
                lines.append("    primary_key: yes")
            lines.append(f'    label: "{escape_lookml_string(col_name)}"')
            if description:
                lines.append(f'    description: "{escape_lookml_string(description)}"')
            lines.append(f"    type: {ftype}")
            lines.append(f"    sql: ${{TABLE}}.{sql_col} ;;")
            if hidden:
                lines.append("    hidden: yes")
            lines.append("  }")
            lines.append("")

    # Primary key first
    if pk_col:
        pk_meta = next((c for c in columns if c["column_name"] == pk_col), None)
        emit_dimension(
            pk_col,
            pk_meta.get("data_type") if pk_meta else None,
            pk_meta.get("pandas_dtype") if pk_meta else None,
            primary=True,
            description="Inferred primary key from Phase 1 inventory naming.",
        )

    for c in columns:
        cname = c["column_name"]
        if pk_col and cname == pk_col:
            continue
        emit_dimension(
            cname,
            c.get("data_type"),
            c.get("pandas_dtype"),
            description=c.get("description"),
            hidden=bool(c.get("hidden")),
        )

    # Calculated columns as dimensions (warehouse preferred)
    for cc in calc_cols:
        cname = cc.get("column_name") or cc.get("name")
        if not cname:
            continue
        if (tname, cname) in field_name_map:
            continue
        fname = lookml_field_name(cname)
        base = fname
        i = 2
        while fname in used_fields:
            fname = f"{base}_{i}"
            i += 1
        used_fields.add(fname)
        field_name_map[(tname, cname)] = fname
        expr = cc.get("expression") or ""
        lines.append(f"  dimension: {fname} {{")
        lines.append(f'    label: "{escape_lookml_string(cname)}"')
        lines.append(
            f'    description: "PBI calculated column. Prefer warehouse materialization. DAX: {escape_lookml_string(expr[:200])}"'
        )
        lines.append("    type: string")
        lines.append(f"    sql: ${{TABLE}}.{quote_sql_ident(cname)} ;;")
        lines.append("  }")
        lines.append("")

    # Measures attached to this view
    for m in measures_for_view:
        mname = m.get("measure_name") or m.get("name")
        expr = m.get("expression") or ""
        plan = classify_dax(expr, mname or "")
        fname = lookml_field_name(mname)
        base = fname
        i = 2
        while fname in used_fields:
            fname = f"{base}_{i}"
            i += 1
        used_fields.add(fname)
        lines.append(f"  measure: {fname} {{")
        lines.append(f'    label: "{escape_lookml_string(mname)}"')
        lines.append(f'    description: "From Power BI. Strategy={plan.strategy}. DAX: {escape_lookml_string(expr[:180])}"')
        lines.append(f"    type: {plan.lookml_type}")
        if plan.strategy in {"direct_sum", "direct_average", "count_distinct"} and plan.sql:
            dim = field_name_map.get((tname, plan.sql)) or lookml_field_name(plan.sql)
            # Prefer ${dimension} per looker-skills when dimension exists on same view
            if (tname, plan.sql) in field_name_map:
                lines.append(f"    sql: ${{{dim}}} ;;")
            else:
                # column may live on another table — still reference TABLE if same view expected
                lines.append(f"    sql: ${{TABLE}}.{quote_sql_ident(plan.sql)} ;;")
        elif plan.strategy == "direct_count":
            lines.append("    # COUNT — type already set to count; switch to count_distinct on PK if needed.")
        elif plan.strategy == "sum_plus_sum":
            cols = re.findall(r"\[([^\]]+)\]", expr)
            if len(cols) >= 2:
                c1, c2 = cols[0], cols[1]
                lines.append(
                    f"    sql: ${{TABLE}}.{quote_sql_ident(c1)} + ${{TABLE}}.{quote_sql_ident(c2)} ;;"
                )
            else:
                lines.append("    sql: NULL ;;  # TODO: implement sum+sum")
        elif plan.strategy == "sum_over_sum":
            cols = re.findall(r"\[([^\]]+)\]", expr)
            if len(cols) >= 2:
                c1, c2 = cols[0], cols[1]
                lines.append(
                    f"    sql: SAFE_DIVIDE(SUM(${{TABLE}}.{quote_sql_ident(c1)}), SUM(${{TABLE}}.{quote_sql_ident(c2)})) ;;"
                )
            else:
                lines.append("    sql: NULL ;;  # TODO")
        elif plan.strategy == "ratio":
            refs = re.findall(r"\[([^\]]+)\]", expr)
            if len(refs) >= 2:
                a, b = lookml_field_name(refs[0]), lookml_field_name(refs[1])
                lines.append(f"    sql: SAFE_DIVIDE(${{{a}}}, ${{{b}}}) ;;")
            else:
                lines.append("    sql: NULL ;;  # TODO: wire child measures")
            if plan.value_format:
                lines.append(f"    value_format_name: {plan.value_format}")
        elif plan.strategy == "filtered":
            lines.append("    # TODO: implement CALCULATE filter via filters: block or filtered measure")
            for hint, val in plan.filters:
                lines.append(f'    # filter hint: {hint} = "{val}"')
            lines.append("    sql: NULL ;;")
        elif plan.strategy == "parameter_value":
            lines.append("    # TODO: convert SELECTEDVALUE to Looker parameter")
            lines.append("    sql: NULL ;;")
        else:
            lines.append("    # TODO: complex DAX — see description; validate KPI parity before production")
            lines.append("    sql: NULL ;;")
        if plan.value_format and plan.strategy not in {"ratio"}:
            lines.append(f"    value_format_name: {plan.value_format}")
        lines.append("  }")
        lines.append("")

    # Default count
    if "count" not in used_fields:
        lines.append("  measure: count {")
        lines.append("    type: count")
        lines.append(f'    drill_fields: [{lookml_field_name(pk_col) if pk_col else "count"}]')
        lines.append("  }")
        lines.append("")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def pick_fact_table(tables: list[dict], rels: list[dict]) -> str | None:
    from_counts: dict[str, int] = defaultdict(int)
    for r in rels:
        from_counts[r.get("from_table") or ""] += 1
    if from_counts:
        return max(from_counts, key=from_counts.get)
    for t in tables:
        n = t["table_name"]
        if "fact" in n.lower():
            return n
    return tables[0]["table_name"] if tables else None


def render_model(
    model_name: str,
    view_names: list[str],
    fact_table: str | None,
    rels: list[dict],
    field_name_map: dict[tuple[str, str], str],
    source_pbix: str,
) -> str:
    lines: list[str] = []
    lines.append("# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory")
    lines.append(f"# Source PBIX: {source_pbix}")
    lines.append("# Standards: looker-skills (explicit relationship, granular includes, explore description)")
    lines.append("# TODO: set connection to your Looker Admin connection name")
    lines.append('connection: "YOUR_LOOKER_CONNECTION"')
    lines.append("")
    for vn in sorted(view_names):
        lines.append(f'include: "/views/{vn}.view.lkml"')
    lines.append("")
    lines.append(f"datagroup: {model_name}_default_datagroup {{")
    lines.append('  max_cache_age: "24 hours"')
    lines.append("}")
    lines.append("")

    fact_view = lookml_view_name(fact_table) if fact_table else None
    if not fact_view:
        lines.append("# No fact table detected — add explores manually.")
        return "\n".join(lines) + "\n"

    lines.append(f"explore: {fact_view} {{")
    lines.append(f'  label: "{escape_lookml_string(fact_table)}"')
    lines.append(
        f'  description: "Migrated from Power BI ({escape_lookml_string(Path(source_pbix).name)}). KPI parity not yet validated."'
    )
    lines.append(f"  view_name: {fact_view}")
    lines.append("")

    # Order joins so that a join whose left table is not the fact appears after that left view is joined
    ordered: list[dict] = []
    remaining = [r for r in rels if not is_internal_table(r.get("from_table") or "") and not is_internal_table(r.get("to_table") or "")]
    joined_views = {fact_view}
    guard = 0
    while remaining and guard < 100:
        guard += 1
        progress = False
        for r in list(remaining):
            left_view = lookml_view_name(r.get("from_table") or "")
            if left_view == fact_view or left_view in joined_views:
                ordered.append(r)
                joined_views.add(lookml_view_name(r.get("to_table") or ""))
                remaining.remove(r)
                progress = True
        if not progress:
            ordered.extend(remaining)
            break

    # Track join aliases when same to_table appears twice
    used_join_names: dict[str, int] = defaultdict(int)

    for r in ordered:
        from_t = r.get("from_table")
        to_t = r.get("to_table")
        from_c = r.get("from_column")
        to_c = r.get("to_column")
        left_view = lookml_view_name(from_t)
        right_view = lookml_view_name(to_t)
        used_join_names[right_view] += 1
        join_name = right_view
        from_clause = None
        if used_join_names[right_view] > 1:
            # e.g. second DimDate join on post date
            join_name = f"{right_view}_{snake_case(from_c)}"
            from_clause = right_view

        rel = cardinality_to_relationship(r.get("cardinality") or "M:1")
        left_field = field_name_map.get((from_t, from_c), lookml_field_name(from_c))
        right_field = field_name_map.get((to_t, to_c), lookml_field_name(to_c))

        active = r.get("active", True)
        lines.append(f"  join: {join_name} {{")
        if from_clause:
            lines.append(f"    from: {from_clause}")
        lines.append(f'    view_label: "{escape_lookml_string(to_t)}"')
        if not active:
            lines.append("    # Power BI relationship was INACTIVE (USERELATIONSHIP-style).")
        lines.append("    type: left_outer")
        lines.append(f"    relationship: {rel}")
        if left_view != fact_view and left_view != join_name:
            lines.append(f"    required_joins: [{left_view}]")
        lines.append(f"    sql_on: ${{{left_view}.{left_field}}} = ${{{join_name}.{right_field}}} ;;")
        lines.append("  }")
        lines.append("")

    lines.append("}")
    lines.append("")

    # Hidden dim explores for QA
    for vn in sorted(view_names):
        if vn == fact_view:
            continue
        lines.append(f"explore: {vn} {{")
        lines.append(f'  label: "{vn} (QA)"')
        lines.append('  description: "Hidden dimension explore for QA."')
        lines.append("  hidden: yes")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def build_mapping_doc(data: dict, plans: list[dict], model_name: str) -> tuple[dict, str]:
    counts = data.get("counts") or {}
    source = counts.get("source_pbix") or data["a1"].get("source_pbix") or "PBIX"
    payload = {
        "approach": "deterministic",
        "source_pbix": source,
        "model_name": model_name,
        "object_equivalence": OBJECT_EQUIVALENCE,
        "generated_objects": plans,
        "references": [
            "https://github.com/looker-open-source/looker-skills",
            "https://cloud.google.com/looker/docs/lookml-terms-and-concepts",
            "https://cloud.google.com/looker/docs/reference/param-view-view",
            "https://cloud.google.com/looker/docs/reference/param-explore-join",
        ],
    }
    lines = [
        f"# Power BI → Looker Object Mapping",
        "",
        f"**Source:** `{Path(source).name}`  ",
        f"**Model:** `{model_name}`  ",
        "**Approach:** deterministic (Phase 2 generator; no LLM)",
        "",
        "## Object equivalence",
        "",
        "| Power BI | Looker | How to create |",
        "|---|---|---|",
    ]
    for row in OBJECT_EQUIVALENCE:
        how = row["how_to_create"].replace("|", "\\|")
        lines.append(f"| {row['power_bi']} | {row['looker']} | {how} |")
    lines += ["", "## Generated objects", ""]
    for p in plans:
        lines.append(f"- **{p['kind']}** `{p.get('power_bi')}` → `{p.get('looker')}` ({p.get('status', 'ok')})")
    lines.append("")
    return payload, "\n".join(lines)


def generate(inv_dir: Path | None = None, out_root: Path | None = None) -> dict:
    data = load_inventory(inv_dir)
    out = out_root or ROOT
    lookml_root = out / "lookml"
    views_dir = lookml_root / "views"
    models_dir = lookml_root / "models"
    views_dir.mkdir(parents=True, exist_ok=True)
    models_dir.mkdir(parents=True, exist_ok=True)

    # clean previous generated views/models
    for p in views_dir.glob("*.view.lkml"):
        p.unlink()
    for p in models_dir.glob("*.model.lkml"):
        p.unlink()

    a1, a2, a3 = data["a1"], data["a2"], data["a3"]
    tables = business_tables(a1)
    cols_map = columns_by_table(a1)
    calc_map = calc_cols_by_table(a2)
    rels = a3.get("relationships") or []
    measures = a2.get("measures") or []
    source = (data.get("counts") or {}).get("source_pbix") or a1.get("source_pbix") or "PBIX"
    model_name = snake_case(Path(source).stem) or "pbix_model"

    fact = pick_fact_table(tables, rels)
    field_name_map: dict[tuple[str, str], str] = {}
    plans: list[dict] = []

    # Assign measures to views: prefer expression's table, else fact, else Measure Table → fact
    measures_by_view: dict[str, list[dict]] = defaultdict(list)
    for m in measures:
        expr = m.get("expression") or ""
        tbl, _ = extract_table_column(expr)
        host = tbl if tbl and not is_internal_table(tbl) else fact
        # Measure Table is not a real physical table in this inventory
        if host and host.lower().replace(" ", "") in {"measuretable", "measures"}:
            host = fact
        if not host:
            host = fact
        # If table not in business list, attach to fact
        biz_names = {t["table_name"] for t in tables}
        if host not in biz_names:
            # try case-insensitive
            match = next((n for n in biz_names if n.lower() == (host or "").lower()), None)
            host = match or fact
        measures_by_view[host].append(m)
        plan = classify_dax(expr, m.get("measure_name") or "")
        plans.append(
            {
                "kind": "measure",
                "power_bi": f"{m.get('table')}.{m.get('measure_name')}",
                "looker": f"measure:{lookml_field_name(m.get('measure_name') or '')}",
                "strategy": plan.strategy,
                "status": "todo" if plan.strategy in {"complex_todo", "filtered", "parameter_value"} else "mapped",
            }
        )

    view_names: list[str] = []
    for t in tables:
        tname = t["table_name"]
        vname = lookml_view_name(tname)
        view_names.append(vname)
        body = render_view(
            t,
            cols_map.get(tname, []),
            calc_map.get(tname, []),
            measures_by_view.get(tname, []),
            field_name_map,
        )
        (views_dir / f"{vname}.view.lkml").write_text(body)
        plans.append(
            {
                "kind": "view",
                "power_bi": tname,
                "looker": f"views/{vname}.view.lkml",
                "status": "mapped",
            }
        )

    # Joins
    for r in rels:
        plans.append(
            {
                "kind": "join",
                "power_bi": f"{r.get('from_table')}[{r.get('from_column')}] -> {r.get('to_table')}[{r.get('to_column')}]",
                "looker": f"explore join relationship={cardinality_to_relationship(r.get('cardinality') or '')}",
                "status": "mapped" if r.get("active", True) else "inactive_alias",
            }
        )

    model_body = render_model(model_name, view_names, fact, rels, field_name_map, source)
    model_path = models_dir / f"{model_name}.model.lkml"
    model_path.write_text(model_body)

    # manifest
    (lookml_root / "manifest.lkml").write_text(
        "# LookML project manifest — generated by phase2\n"
        f'# Source: {Path(source).name}\n'
        "project_name: \"pbix_to_looker_phase2\"\n"
    )
    (lookml_root / "README.md").write_text(
        f"# LookML project (Phase 2)\n\n"
        f"Generated deterministically from Phase 1 inventory for `{Path(source).name}`.\n\n"
        f"- Model: `models/{model_name}.model.lkml`\n"
        f"- Views: `views/*.view.lkml`\n"
        f"- Set `connection:` and `sql_table_name` project/dataset placeholders before validating in Looker.\n"
        f"- KPI parity is **not** validated automatically.\n"
    )

    mapping_json, mapping_md = build_mapping_doc(data, plans, model_name)
    (out / "OBJECT_MAPPING.json").write_text(json.dumps(mapping_json, indent=2))
    (out / "OBJECT_MAPPING.md").write_text(mapping_md)

    return {
        "model": str(model_path),
        "views": len(view_names),
        "measures": len(measures),
        "relationships": len(rels),
        "model_name": model_name,
        "fact": fact,
        "source_pbix": source,
    }


if __name__ == "__main__":
    info = generate()
    print(json.dumps(info, indent=2))
