# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source PBIX: /Users/Basavaraj_Angadi/Desktop/data eng /phase1/uploads/Human Resources Sample PBIX.pbix
# Standards: looker-skills (explicit relationship, granular includes, explore description)
# TODO: set connection to your Looker Admin connection name
connection: "YOUR_LOOKER_CONNECTION"

include: "/views/agegroup.view.lkml"
include: "/views/bu.view.lkml"
include: "/views/date.view.lkml"
include: "/views/employee.view.lkml"
include: "/views/ethnicity.view.lkml"
include: "/views/fp.view.lkml"
include: "/views/gender.view.lkml"
include: "/views/paytype.view.lkml"
include: "/views/separationreason.view.lkml"

datagroup: human_resources_sample_pbix_default_datagroup {
  max_cache_age: "24 hours"
}

explore: employee {
  label: "Employee"
  description: "Migrated from Power BI (Human Resources Sample PBIX.pbix). KPI parity not yet validated."
  view_name: employee

  join: date {
    view_label: "Date"
    type: left_outer
    relationship: many_to_one
    sql_on: ${employee.date_key} = ${date.date_key} ;;
  }

  join: fp {
    view_label: "FP"
    type: left_outer
    relationship: many_to_one
    sql_on: ${employee.fp} = ${fp.fp} ;;
  }

  join: ethnicity {
    view_label: "Ethnicity"
    type: left_outer
    relationship: many_to_one
    sql_on: ${employee.ethnicgroup} = ${ethnicity.ethnic_group} ;;
  }

  join: gender {
    view_label: "Gender"
    type: left_outer
    relationship: many_to_one
    sql_on: ${employee.gender} = ${gender.id} ;;
  }

  join: paytype {
    view_label: "PayType"
    type: left_outer
    relationship: many_to_one
    sql_on: ${employee.paytypeid} = ${paytype.paytypeid} ;;
  }

  join: bu {
    view_label: "BU"
    type: left_outer
    relationship: many_to_one
    sql_on: ${employee.bu} = ${bu.bu} ;;
  }

  join: agegroup {
    view_label: "AgeGroup"
    type: left_outer
    relationship: many_to_one
    sql_on: ${employee.agegroupid} = ${agegroup.agegroupid} ;;
  }

  join: separationreason {
    view_label: "SeparationReason"
    type: left_outer
    relationship: many_to_one
    sql_on: ${employee.termreason} = ${separationreason.separationtypeid} ;;
  }

}

explore: agegroup {
  label: "agegroup (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: bu {
  label: "bu (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: date {
  label: "date (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: ethnicity {
  label: "ethnicity (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: fp {
  label: "fp (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: gender {
  label: "gender (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: paytype {
  label: "paytype (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: separationreason {
  label: "separationreason (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}
