# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source PBIX: /Users/Basavaraj_Angadi/Desktop/data eng /phase1/uploads/movie_rental_analysis.pbix
# Standards: looker-skills (explicit relationship, granular includes, explore description)
# TODO: set connection to your Looker Admin connection name
connection: "YOUR_LOOKER_CONNECTION"

include: "/views/actor.view.lkml"
include: "/views/address.view.lkml"
include: "/views/category.view.lkml"
include: "/views/city.view.lkml"
include: "/views/country.view.lkml"
include: "/views/customer.view.lkml"
include: "/views/film.view.lkml"
include: "/views/film_actor.view.lkml"
include: "/views/film_category.view.lkml"
include: "/views/film_text.view.lkml"
include: "/views/inventory.view.lkml"
include: "/views/language.view.lkml"
include: "/views/payment.view.lkml"
include: "/views/rentat.view.lkml"
include: "/views/staff.view.lkml"
include: "/views/store.view.lkml"

datagroup: movie_rental_analysis_default_datagroup {
  max_cache_age: "24 hours"
}

explore: film {
  label: "film"
  description: "Migrated from Power BI (movie_rental_analysis.pbix). KPI parity not yet validated."
  view_name: film

  join: language {
    view_label: "language"
    type: left_outer
    relationship: many_to_one
    sql_on: ${film.language_id} = ${language.language_id} ;;
  }

  join: film_category {
    view_label: "film_category"
    type: left_outer
    relationship: many_to_one
    sql_on: ${film.film_id} = ${film_category.film_id} ;;
  }

  join: film_text {
    view_label: "film_text"
    type: left_outer
    relationship: many_to_one
    sql_on: ${film.film_id} = ${film_text.film_id} ;;
  }

  join: category {
    view_label: "category"
    type: left_outer
    relationship: many_to_one
    required_joins: [film_category]
    sql_on: ${film_category.category_id} = ${category.category_id} ;;
  }

  join: actor {
    view_label: "actor"
    type: left_outer
    relationship: many_to_one
    required_joins: [film_actor]
    sql_on: ${film_actor.actor_id} = ${actor.actor_id} ;;
  }

  join: city {
    view_label: "city"
    type: left_outer
    relationship: many_to_one
    required_joins: [address]
    sql_on: ${address.city_id} = ${city.city_id} ;;
  }

  join: country {
    view_label: "country"
    type: left_outer
    relationship: many_to_one
    required_joins: [city]
    sql_on: ${city.country_id} = ${country.country_id} ;;
  }

  join: staff {
    view_label: "staff"
    type: left_outer
    relationship: many_to_one
    required_joins: [store]
    sql_on: ${store.store_id} = ${staff.store_id} ;;
  }

  join: film {
    view_label: "film"
    type: left_outer
    relationship: many_to_one
    required_joins: [film_actor]
    sql_on: ${film_actor.film_id} = ${film.film_id} ;;
  }

  join: address {
    view_label: "address"
    type: left_outer
    relationship: many_to_one
    required_joins: [customer]
    sql_on: ${customer.address_id} = ${address.address_id} ;;
  }

  join: customer {
    view_label: "customer"
    type: left_outer
    relationship: many_to_one
    required_joins: [payment]
    sql_on: ${payment.customer_id} = ${customer.customer_id} ;;
  }

  join: store {
    view_label: "store"
    type: left_outer
    relationship: many_to_one
    required_joins: [customer]
    sql_on: ${customer.store_id} = ${store.store_id} ;;
  }

  join: inventory {
    view_label: "inventory"
    type: left_outer
    relationship: many_to_one
    required_joins: [rentat]
    sql_on: ${rentat.inventory_id} = ${inventory.inventory_id} ;;
  }

  join: payment {
    view_label: "payment"
    type: left_outer
    relationship: many_to_one
    required_joins: [rentat]
    sql_on: ${rentat.rental_id} = ${payment.rental_id} ;;
  }

  join: staff_staff_id {
    from: staff
    view_label: "staff"
    # Power BI relationship was INACTIVE (USERELATIONSHIP-style).
    type: left_outer
    relationship: many_to_one
    required_joins: [rentat]
    sql_on: ${rentat.staff_id} = ${staff_staff_id.staff_id} ;;
  }

  join: film_film_id {
    from: film
    view_label: "film"
    type: left_outer
    relationship: many_to_one
    required_joins: [inventory]
    sql_on: ${inventory.film_id} = ${film_film_id.film_id} ;;
  }

}

explore: actor {
  label: "actor (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: address {
  label: "address (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: category {
  label: "category (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: city {
  label: "city (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: country {
  label: "country (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: customer {
  label: "customer (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: film_actor {
  label: "film_actor (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: film_category {
  label: "film_category (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: film_text {
  label: "film_text (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: inventory {
  label: "inventory (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: language {
  label: "language (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: payment {
  label: "payment (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: rentat {
  label: "rentat (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: staff {
  label: "staff (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}

explore: store {
  label: "store (QA)"
  description: "Hidden dimension explore for QA."
  hidden: yes
}
