# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: actor
view: actor {
  label: "actor"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.actor` ;;

  dimension: actor_id {
    primary_key: yes
    label: "actor_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.actor_id ;;
  }

  dimension: first_name {
    label: "first_name"
    type: string
    sql: ${TABLE}.first_name ;;
  }

  dimension: last_name {
    label: "last_name"
    type: string
    sql: ${TABLE}.last_name ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: count {
    type: count
    drill_fields: [actor_id]
  }

}
