# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: actor
# Standards: looker-open-source/looker-skills + Google Looker docs
# - primary_key first; measures reference ${dimension} where possible
# - measure-of-measures → type: number; ratios use 1.0 * x / NULLIF(y, 0)
# - filters: only on aggregate measure types (not type: number)
view: actor {
  label: "actor"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.actor` ;;

  dimension: actor_id {
    primary_key: yes
    label: "actor_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.actor_id ;;
  }

  dimension: first_name {
    label: "first_name"
    type: string
    sql: ${TABLE}.first_name ;;
  }

  dimension: last_name {
    label: "last_name"
    type: string
    sql: ${TABLE}.last_name ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: film_popularity {
    label: "FilmPopularity"
    description: "From Power BI measure `FilmPopularity`. Strategy=complex_todo. Complex / filter / time-intel DAX — implement with LookML period patterns, filtered aggregate measures, or warehouse metrics. Do not claim KPI parity until side-by-side validation. DAX: SUMX('film',COUNT(film[rental_rate])
)"
    type: number
    # TODO: complex DAX — keep original expression; validate KPI parity before production
    sql: NULL ;;
  }

  measure: count {
    type: count
    drill_fields: [actor_id]
  }

}
