# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: address
# Standards: looker-open-source/looker-skills + Google Looker docs
# - primary_key first; measures reference ${dimension} where possible
# - measure-of-measures → type: number; ratios use 1.0 * x / NULLIF(y, 0)
# - filters: only on aggregate measure types (not type: number)
view: address {
  label: "address"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.address` ;;

  dimension: address_id {
    primary_key: yes
    label: "address_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.address_id ;;
  }

  dimension: address {
    label: "address"
    type: string
    sql: ${TABLE}.address ;;
  }

  dimension: address2 {
    label: "address2"
    type: string
    sql: ${TABLE}.address2 ;;
  }

  dimension: district {
    label: "district"
    type: string
    sql: ${TABLE}.district ;;
  }

  dimension: city_id {
    label: "city_id"
    type: number
    sql: ${TABLE}.city_id ;;
  }

  dimension: postal_code {
    label: "postal_code"
    type: number
    sql: ${TABLE}.postal_code ;;
  }

  dimension: phone {
    label: "phone"
    type: number
    sql: ${TABLE}.phone ;;
  }

  dimension: location {
    label: "location"
    type: string
    sql: ${TABLE}.location ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: count {
    type: count
    drill_fields: [address_id]
  }

}
