# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: AgeGroup
view: agegroup {
  label: "AgeGroup"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.agegroup` ;;

  dimension: agegroupid {
    primary_key: yes
    label: "AgeGroupID"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.AgeGroupID ;;
  }

  dimension: agegroup {
    label: "AgeGroup"
    type: string
    sql: ${TABLE}.AgeGroup ;;
  }

  measure: count {
    type: count
    drill_fields: [agegroupid]
  }

}
