# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: BU
view: bu {
  label: "BU"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.bu` ;;

  dimension: bu {
    primary_key: yes
    label: "BU"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: string
    sql: ${TABLE}.BU ;;
  }

  dimension: regionseq {
    label: "RegionSeq"
    type: string
    sql: ${TABLE}.RegionSeq ;;
  }

  dimension: vp {
    label: "VP"
    type: string
    sql: ${TABLE}.VP ;;
  }

  dimension: region {
    label: "Region"
    type: string
    sql: ${TABLE}.Region ;;
  }

  measure: count_of_bu {
    label: "Count of BU"
    description: "From Power BI. Strategy=complex_todo. DAX: COUNTA('BU'[BU])"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: count {
    type: count
    drill_fields: [bu]
  }

}
