# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: city
# Standards: looker-open-source/looker-skills + Google Looker docs
# - primary_key first; measures reference ${dimension} where possible
# - measure-of-measures → type: number; ratios use 1.0 * x / NULLIF(y, 0)
# - filters: only on aggregate measure types (not type: number)
view: city {
  label: "city"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.city` ;;

  dimension: city_id {
    primary_key: yes
    label: "city_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.city_id ;;
  }

  dimension: city {
    label: "city"
    type: string
    sql: ${TABLE}.city ;;
  }

  dimension: country_id {
    label: "country_id"
    type: number
    sql: ${TABLE}.country_id ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: count {
    type: count
    drill_fields: [city_id]
  }

}
