# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: country
view: country {
  label: "country"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.country` ;;

  dimension: country_id {
    primary_key: yes
    label: "country_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.country_id ;;
  }

  dimension: country {
    label: "country"
    type: string
    sql: ${TABLE}.country ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: count {
    type: count
    drill_fields: [country_id]
  }

}
