# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: customer
view: customer {
  label: "customer"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.customer` ;;

  dimension: customer_id {
    primary_key: yes
    label: "customer_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.customer_id ;;
  }

  dimension: store_id {
    label: "store_id"
    type: number
    sql: ${TABLE}.store_id ;;
  }

  dimension: first_name {
    label: "first_name"
    type: string
    sql: ${TABLE}.first_name ;;
  }

  dimension: last_name {
    label: "last_name"
    type: string
    sql: ${TABLE}.last_name ;;
  }

  dimension: email {
    label: "email"
    type: string
    sql: ${TABLE}.email ;;
  }

  dimension: address_id {
    label: "address_id"
    type: number
    sql: ${TABLE}.address_id ;;
  }

  dimension: active {
    label: "active"
    type: number
    sql: ${TABLE}.active ;;
  }

  dimension_group: create_date {
    label: "create_date"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.create_date ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  dimension: employment_duration {
    label: "Employment Duration"
    type: number
    sql: ${TABLE}.`Employment Duration` ;;
  }

  measure: count {
    type: count
    drill_fields: [customer_id]
  }

}
