# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: Date
view: date {
  label: "Date"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.date` ;;

  dimension_group: date {
    label: "Date"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.Date ;;
    # NOTE: time primary keys are unusual; prefer a date_raw key if needed
  }

  dimension: date_key {
    primary_key: yes
    label: "Date Key"
    type: date
    sql: ${TABLE}.Date ;;
    hidden: yes
  }

  dimension: month {
    label: "Month"
    type: string
    sql: ${TABLE}.Month ;;
  }

  dimension: monthnumber {
    label: "MonthNumber"
    type: number
    sql: ${TABLE}.MonthNumber ;;
  }

  dimension: period {
    label: "Period"
    type: string
    sql: ${TABLE}.Period ;;
  }

  dimension: periodnumber {
    label: "PeriodNumber"
    type: number
    sql: ${TABLE}.PeriodNumber ;;
  }

  dimension: qtr {
    label: "Qtr"
    type: number
    sql: ${TABLE}.Qtr ;;
  }

  dimension: qtrnumber {
    label: "QtrNumber"
    type: string
    sql: ${TABLE}.QtrNumber ;;
  }

  dimension: year {
    label: "Year"
    type: number
    sql: ${TABLE}.Year ;;
  }

  dimension: day {
    label: "Day"
    type: number
    sql: ${TABLE}.Day ;;
  }

  dimension_group: monthstartdate {
    label: "MonthStartDate"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.MonthStartDate ;;
  }

  dimension_group: monthenddate {
    label: "MonthEndDate"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.MonthEndDate ;;
  }

  dimension: monthincrementnumber {
    label: "MonthIncrementNumber"
    type: number
    sql: ${TABLE}.MonthIncrementNumber ;;
    hidden: yes
  }

  measure: empcount {
    label: "EmpCount"
    description: "From Power BI. Strategy=complex_todo. DAX: CALCULATE(COUNT([EmplID]), FILTER(ALL('Date'[PeriodNumber]), 'Date'[PeriodNumber] = MAX('Date'[PeriodNumber])))"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: new_hires_sply {
    label: "New Hires SPLY"
    description: "From Power BI. Strategy=complex_todo. DAX: CALCULATE([New Hires],SAMEPERIODLASTYEAR('Date'[Date]))"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: actives_sply {
    label: "Actives SPLY"
    description: "From Power BI. Strategy=complex_todo. DAX: CALCULATE([Actives],SAMEPERIODLASTYEAR('Date'[Date]))"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: seps_sply {
    label: "Seps SPLY"
    description: "From Power BI. Strategy=complex_todo. DAX: CALCULATE([Seps],SAMEPERIODLASTYEAR('Date'[Date]))"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: empcount_sply {
    label: "EmpCount SPLY"
    description: "From Power BI. Strategy=complex_todo. DAX: CALCULATE(COUNT([EmplID]), FILTER(ALL('Date'[PeriodNumber]), 'Date'[PeriodNumber] = MAX('Date'[PeriodNumber])),SAMEPERIODLASTYEAR('Date'[Date]))"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: bad_hires_sply {
    label: "Bad Hires SPLY"
    description: "From Power BI. Strategy=complex_todo. DAX: CALCULATE([Sum of BadHires],SAMEPERIODLASTYEAR('Date'[Date]))"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: count_of_date {
    label: "Count of Date"
    description: "From Power BI. Strategy=complex_todo. DAX: COUNTA('Date'[Date])"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: count {
    type: count
    drill_fields: [date]
  }

}
