# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: Employee
view: employee {
  label: "Employee"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.employee` ;;

  dimension_group: date {
    label: "date"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.date ;;
    # NOTE: time primary keys are unusual; prefer a date_raw key if needed
  }

  dimension: date_key {
    primary_key: yes
    label: "date Key"
    type: date
    sql: ${TABLE}.date ;;
    hidden: yes
  }

  dimension: emplid {
    label: "EmplID"
    type: number
    sql: ${TABLE}.EmplID ;;
    hidden: yes
  }

  dimension: gender {
    label: "Gender"
    type: string
    sql: ${TABLE}.Gender ;;
    hidden: yes
  }

  dimension: age {
    label: "Age"
    type: number
    sql: ${TABLE}.Age ;;
    hidden: yes
  }

  dimension: ethnicgroup {
    label: "EthnicGroup"
    type: string
    sql: ${TABLE}.EthnicGroup ;;
    hidden: yes
  }

  dimension: fp {
    label: "FP"
    type: string
    sql: ${TABLE}.FP ;;
    hidden: yes
  }

  dimension_group: termdate {
    label: "TermDate"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.TermDate ;;
    hidden: yes
  }

  dimension: isnewhire {
    label: "isNewHire"
    type: number
    sql: ${TABLE}.isNewHire ;;
    hidden: yes
  }

  dimension: bu {
    label: "BU"
    type: string
    sql: ${TABLE}.BU ;;
    hidden: yes
  }

  dimension_group: hiredate {
    label: "HireDate"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.HireDate ;;
    hidden: yes
  }

  dimension: paytypeid {
    label: "PayTypeID"
    type: string
    sql: ${TABLE}.PayTypeID ;;
    hidden: yes
  }

  dimension: termreason {
    label: "TermReason"
    type: string
    sql: ${TABLE}.TermReason ;;
    hidden: yes
  }

  dimension: agegroupid {
    label: "AgeGroupID"
    type: number
    sql: ${TABLE}.AgeGroupID ;;
    hidden: yes
  }

  dimension: tenuredays {
    label: "TenureDays"
    type: number
    sql: ${TABLE}.TenureDays ;;
    hidden: yes
  }

  dimension: tenuremonths {
    label: "TenureMonths"
    type: number
    sql: ${TABLE}.TenureMonths ;;
    hidden: yes
  }

  dimension: badhires {
    label: "BadHires"
    type: number
    sql: ${TABLE}.BadHires ;;
  }

  measure: seps {
    label: "Seps"
    description: "From Power BI. Strategy=complex_todo. DAX: CALCULATE(COUNT([EmplID]), FILTER(Employee, NOT(ISBLANK(Employee[TermDate]))))"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: actives {
    label: "Actives"
    description: "From Power BI. Strategy=complex_todo. DAX: CALCULATE([EmpCount], FILTER(Employee, ISBLANK(Employee[TermDate])))"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: new_hires {
    label: "New Hires"
    description: "From Power BI. Strategy=complex_todo. DAX: SUM([isNewHire])"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: avg_tenure_days {
    label: "AVG Tenure Days"
    description: "From Power BI. Strategy=complex_todo. DAX: AVERAGE([TenureDays])"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: avg_tenure_months {
    label: "AVG Tenure Months"
    description: "From Power BI. Strategy=complex_todo. DAX: ROUND([AVG Tenure Days]/30, 1)-1"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: avg_age {
    label: "AVG Age"
    description: "From Power BI. Strategy=complex_todo. DAX: ROUND(AVERAGE([Age]), 0)"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: sum_of_badhires {
    label: "Sum of BadHires"
    description: "From Power BI. Strategy=complex_todo. DAX: SUM([BadHires])"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: seps_yoy_var {
    label: "Seps YoY Var"
    description: "From Power BI. Strategy=complex_todo. DAX: [Seps]-[Seps SPLY]"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: actives_yoy_var {
    label: "Actives YoY Var"
    description: "From Power BI. Strategy=complex_todo. DAX: [Actives]-[Actives SPLY]"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: new_hires_yoy_var {
    label: "New Hires YoY Var"
    description: "From Power BI. Strategy=complex_todo. DAX: [New Hires]-[New Hires SPLY]"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: seps_yoy_pct_change {
    label: "Seps YoY % Change"
    description: "From Power BI. Strategy=ratio. DAX: DIVIDE([Seps YoY Var], [Seps SPLY])"
    type: number
    sql: SAFE_DIVIDE(${seps_yoy_var}, ${seps_sply}) ;;
    value_format_name: percent_2
  }

  measure: actives_yoy_pct_change {
    label: "Actives YoY % Change"
    description: "From Power BI. Strategy=ratio. DAX: DIVIDE([Actives YoY Var], [Actives SPLY])"
    type: number
    sql: SAFE_DIVIDE(${actives_yoy_var}, ${actives_sply}) ;;
    value_format_name: percent_2
  }

  measure: new_hires_yoy_pct_change {
    label: "New Hires YoY % Change"
    description: "From Power BI. Strategy=ratio. DAX: DIVIDE([New Hires YoY Var], [New Hires SPLY])"
    type: number
    sql: SAFE_DIVIDE(${new_hires_yoy_var}, ${new_hires_sply}) ;;
    value_format_name: percent_2
  }

  measure: bad_hires_yoy_var {
    label: "Bad Hires YoY Var"
    description: "From Power BI. Strategy=complex_todo. DAX: [Sum of BadHires]-[Bad Hires SPLY]"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: bad_hires_yoy_pct_change {
    label: "Bad Hires YoY % Change"
    description: "From Power BI. Strategy=ratio. DAX: DIVIDE([Bad Hires YoY Var], [Bad Hires SPLY])"
    type: number
    sql: SAFE_DIVIDE(${bad_hires_yoy_var}, ${bad_hires_sply}) ;;
    value_format_name: percent_2
  }

  measure: to_pct {
    label: "TO %"
    description: "From Power BI. Strategy=ratio. DAX: DIVIDE([Seps], [Actives])"
    type: number
    sql: SAFE_DIVIDE(${seps}, ${actives}) ;;
    value_format_name: percent_2
  }

  measure: to_pct_var {
    label: "TO % Var"
    description: "From Power BI. Strategy=complex_todo. DAX: [TO %]-[TO % Norm]"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: seppctofactive {
    label: "Sep%ofActive"
    description: "From Power BI. Strategy=ratio. DAX: DIVIDE([Seps],[Actives])"
    type: number
    sql: SAFE_DIVIDE(${seps}, ${actives}) ;;
    value_format_name: percent_2
  }

  measure: seppctofsmlyactives {
    label: "Sep%ofSMLYActives"
    description: "From Power BI. Strategy=ratio. DAX: DIVIDE([Seps SPLY],[Actives SPLY])"
    type: number
    sql: SAFE_DIVIDE(${seps_sply}, ${actives_sply}) ;;
    value_format_name: percent_2
  }

  measure: badhirepctofactives {
    label: "BadHire%ofActives"
    description: "From Power BI. Strategy=ratio. DAX: DIVIDE([Sum of BadHires],[Actives])"
    type: number
    sql: SAFE_DIVIDE(${sum_of_badhires}, ${actives}) ;;
    value_format_name: percent_2
  }

  measure: badhirepctofactivesply {
    label: "BadHire%ofActiveSPLY"
    description: "From Power BI. Strategy=ratio. DAX: DIVIDE([Bad Hires SPLY],[Actives SPLY])"
    type: number
    sql: SAFE_DIVIDE(${bad_hires_sply}, ${actives_sply}) ;;
    value_format_name: percent_2
  }

  measure: count {
    type: count
    drill_fields: [date]
  }

}
