# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: Ethnicity
view: ethnicity {
  label: "Ethnicity"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.ethnicity` ;;

  dimension: ethnic_group {
    primary_key: yes
    label: "Ethnic Group"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: string
    sql: ${TABLE}.`Ethnic Group` ;;
  }

  dimension: ethnicity {
    label: "Ethnicity"
    type: string
    sql: ${TABLE}.Ethnicity ;;
  }

  measure: count {
    type: count
    drill_fields: [ethnic_group]
  }

}
