# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: film
view: film {
  label: "film"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.film` ;;

  dimension: film_id {
    primary_key: yes
    label: "film_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.film_id ;;
  }

  dimension: title {
    label: "title"
    type: string
    sql: ${TABLE}.title ;;
  }

  dimension: description {
    label: "description"
    type: string
    sql: ${TABLE}.description ;;
  }

  dimension: release_year {
    label: "release_year"
    type: number
    sql: ${TABLE}.release_year ;;
  }

  dimension: language_id {
    label: "language_id"
    type: number
    sql: ${TABLE}.language_id ;;
  }

  dimension: original_language_id {
    label: "original_language_id"
    type: number
    sql: ${TABLE}.original_language_id ;;
  }

  dimension: rental_duration {
    label: "rental_duration"
    type: number
    sql: ${TABLE}.rental_duration ;;
  }

  dimension: rental_rate {
    label: "rental_rate"
    type: number
    sql: ${TABLE}.rental_rate ;;
  }

  dimension: length {
    label: "length"
    type: number
    sql: ${TABLE}.length ;;
  }

  dimension: replacement_cost {
    label: "replacement_cost"
    type: number
    sql: ${TABLE}.replacement_cost ;;
  }

  dimension: rating {
    label: "rating"
    type: string
    sql: ${TABLE}.rating ;;
  }

  dimension: special_features {
    label: "special_features"
    type: string
    sql: ${TABLE}.special_features ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: total_films_rented {
    label: "Total Films Rented"
    description: "From Power BI. Strategy=complex_todo. DAX: COUNTROWS('inventory')"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: average_inventory_value {
    label: "Average Inventory Value"
    description: "From Power BI. Strategy=direct_average. DAX: AVERAGE('film'[rental_rate])"
    type: average
    sql: ${rental_rate} ;;
  }

  measure: inventory_turnover_rate {
    label: "Inventory Turnover Rate"
    description: "From Power BI. Strategy=ratio. DAX: [Total Films Rented] / [Average Inventory Value]
"
    type: number
    sql: SAFE_DIVIDE(${total_films_rented}, ${average_inventory_value}) ;;
    value_format_name: decimal_2
  }

  measure: filmpopularity {
    label: "FilmPopularity"
    description: "From Power BI. Strategy=complex_todo. DAX: SUMX('film',COUNT(film[rental_rate])
)"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: count {
    type: count
    drill_fields: [film_id]
  }

}
