# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: film_actor
view: film_actor {
  label: "film_actor"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.film_actor` ;;

  dimension: actor_id {
    primary_key: yes
    label: "actor_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.actor_id ;;
  }

  dimension: film_id {
    label: "film_id"
    type: number
    sql: ${TABLE}.film_id ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: count {
    type: count
    drill_fields: [actor_id]
  }

}
