# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: film
# Standards: looker-open-source/looker-skills + Google Looker docs
# - primary_key first; measures reference ${dimension} where possible
# - measure-of-measures → type: number; ratios use 1.0 * x / NULLIF(y, 0)
# - filters: only on aggregate measure types (not type: number)
view: film {
  label: "film"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.film` ;;

  dimension: film_id {
    primary_key: yes
    label: "film_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.film_id ;;
  }

  dimension: title {
    label: "title"
    type: string
    sql: ${TABLE}.title ;;
  }

  dimension: description {
    label: "description"
    type: string
    sql: ${TABLE}.description ;;
  }

  dimension: release_year {
    label: "release_year"
    type: number
    sql: ${TABLE}.release_year ;;
  }

  dimension: language_id {
    label: "language_id"
    type: number
    sql: ${TABLE}.language_id ;;
  }

  dimension: original_language_id {
    label: "original_language_id"
    type: number
    sql: ${TABLE}.original_language_id ;;
  }

  dimension: rental_duration {
    label: "rental_duration"
    type: number
    sql: ${TABLE}.rental_duration ;;
  }

  dimension: rental_rate {
    label: "rental_rate"
    type: number
    sql: ${TABLE}.rental_rate ;;
  }

  dimension: length {
    label: "length"
    type: number
    sql: ${TABLE}.length ;;
  }

  dimension: replacement_cost {
    label: "replacement_cost"
    type: number
    sql: ${TABLE}.replacement_cost ;;
  }

  dimension: rating {
    label: "rating"
    type: string
    sql: ${TABLE}.rating ;;
  }

  dimension: special_features {
    label: "special_features"
    type: string
    sql: ${TABLE}.special_features ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: count {
    type: count
    drill_fields: [film_id]
  }

}
