# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: film_text
# Standards: looker-open-source/looker-skills + Google Looker docs
# - primary_key first; measures reference ${dimension} where possible
# - measure-of-measures → type: number; ratios use 1.0 * x / NULLIF(y, 0)
# - filters: only on aggregate measure types (not type: number)
view: film_text {
  label: "film_text"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.film_text` ;;

  dimension: film_id {
    primary_key: yes
    label: "film_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.film_id ;;
  }

  dimension: title {
    label: "title"
    type: string
    sql: ${TABLE}.title ;;
  }

  dimension: description {
    label: "description"
    type: string
    sql: ${TABLE}.description ;;
  }

  measure: count {
    type: count
    drill_fields: [film_id]
  }

}
