# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: film_category
view: film_category {
  label: "film_category"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.film_category` ;;

  dimension: film_id {
    primary_key: yes
    label: "film_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.film_id ;;
  }

  dimension: category_id {
    label: "category_id"
    type: number
    sql: ${TABLE}.category_id ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: count {
    type: count
    drill_fields: [film_id]
  }

}
