# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: FP
view: fp {
  label: "FP"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.fp` ;;

  dimension: fp {
    primary_key: yes
    label: "FP"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: string
    sql: ${TABLE}.FP ;;
  }

  dimension: fpdesc {
    label: "FPDesc"
    type: string
    sql: ${TABLE}.FPDesc ;;
  }

  measure: count {
    type: count
    drill_fields: [fp]
  }

}
