# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: Gender
view: gender {
  label: "Gender"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.gender` ;;

  dimension: id {
    primary_key: yes
    label: "ID"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: string
    sql: ${TABLE}.ID ;;
  }

  dimension: gender {
    label: "Gender"
    type: string
    sql: ${TABLE}.Gender ;;
  }

  dimension: sort {
    label: "Sort"
    type: number
    sql: ${TABLE}.Sort ;;
    hidden: yes
  }

  measure: to_pct_norm {
    label: "TO % Norm"
    description: "From Power BI. Strategy=complex_todo. DAX: CALCULATE([TO %], all(Gender[Gender]), ALL(Ethnicity[Ethnicity]))"
    type: number
    # TODO: complex DAX — see description; validate KPI parity before production
    sql: NULL ;;
  }

  measure: count {
    type: count
    drill_fields: [id]
  }

}
