# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: inventory
# Standards: looker-open-source/looker-skills + Google Looker docs
# - primary_key first; measures reference ${dimension} where possible
# - measure-of-measures → type: number; ratios use 1.0 * x / NULLIF(y, 0)
# - filters: only on aggregate measure types (not type: number)
view: inventory {
  label: "inventory"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.inventory` ;;

  dimension: inventory_id {
    primary_key: yes
    label: "inventory_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.inventory_id ;;
  }

  dimension: film_id {
    label: "film_id"
    type: number
    sql: ${TABLE}.film_id ;;
  }

  dimension: store_id {
    label: "store_id"
    type: number
    sql: ${TABLE}.store_id ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: total_films_rented {
    label: "Total Films Rented"
    description: "From Power BI measure `Total Films Rented`. Strategy=complex_todo. Unclassified DAX — developer review required. Original: COUNTROWS('inventory') DAX: COUNTROWS('inventory')"
    type: number
    # TODO: complex DAX — keep original expression; validate KPI parity before production
    sql: NULL ;;
  }

  measure: average_inventory_value {
    label: "Average Inventory Value"
    description: "From Power BI measure `Average Inventory Value`. Strategy=direct_average. Direct AVERAGE → type: average DAX: AVERAGE('film'[rental_rate])"
    type: average
    sql: ${TABLE}.rental_rate ;;
  }

  measure: inventory_turnover_rate {
    label: "Inventory Turnover Rate"
    description: "From Power BI measure `Inventory Turnover Rate`. Strategy=measure_ratio. DEPENDS ON: Total Films Rented, Average Inventory Value. Implement dependency measures first; this field uses type:number + ${measure} refs. DEPENDS ON: Total Films Rented, Average Inventory Value. Implement those LookML measures first. This measure must be type: number and reference them via ${measure} (Looker: measures based on other measures). DIVIDE/ratio of measures [To"
    type: number
    # DEPENDS ON Power BI measures: Total Films Rented, Average Inventory Value
    # Looker rule: measure-of-measures must be type: number (https://cloud.google.com/looker/docs/reference/param-measure-types)
    sql: 100.0 * ${total_films_rented} / NULLIF(${average_inventory_value}, 0) ;;
    value_format_name: percent_2
  }

  measure: count {
    type: count
    drill_fields: [inventory_id]
  }

}
