# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: inventory
view: inventory {
  label: "inventory"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.inventory` ;;

  dimension: inventory_id {
    primary_key: yes
    label: "inventory_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.inventory_id ;;
  }

  dimension: film_id {
    label: "film_id"
    type: number
    sql: ${TABLE}.film_id ;;
  }

  dimension: store_id {
    label: "store_id"
    type: number
    sql: ${TABLE}.store_id ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: count {
    type: count
    drill_fields: [inventory_id]
  }

}
