# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: language
view: language {
  label: "language"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.language` ;;

  dimension: language_id {
    primary_key: yes
    label: "language_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.language_id ;;
  }

  dimension: name {
    label: "name"
    type: string
    sql: ${TABLE}.name ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: count {
    type: count
    drill_fields: [language_id]
  }

}
