# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: payment
view: payment {
  label: "payment"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.payment` ;;

  dimension: payment_id {
    primary_key: yes
    label: "payment_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.payment_id ;;
  }

  dimension: customer_id {
    label: "customer_id"
    type: number
    sql: ${TABLE}.customer_id ;;
  }

  dimension: staff_id {
    label: "staff_id"
    type: number
    sql: ${TABLE}.staff_id ;;
  }

  dimension: rental_id {
    label: "rental_id"
    type: number
    sql: ${TABLE}.rental_id ;;
  }

  dimension: amount {
    label: "amount"
    type: number
    sql: ${TABLE}.amount ;;
  }

  dimension_group: payment_date {
    label: "payment_date"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.payment_date ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: revenue {
    label: "Revenue"
    description: "From Power BI. Strategy=direct_sum. DAX: SUM(payment[amount])"
    type: sum
    sql: ${amount} ;;
  }

  measure: count {
    type: count
    drill_fields: [payment_id]
  }

}
