# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: payment
# Standards: looker-open-source/looker-skills + Google Looker docs
# - primary_key first; measures reference ${dimension} where possible
# - measure-of-measures → type: number; ratios use 1.0 * x / NULLIF(y, 0)
# - filters: only on aggregate measure types (not type: number)
view: payment {
  label: "payment"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.payment` ;;

  dimension: payment_id {
    primary_key: yes
    label: "payment_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.payment_id ;;
  }

  dimension: customer_id {
    label: "customer_id"
    type: number
    sql: ${TABLE}.customer_id ;;
  }

  dimension: staff_id {
    label: "staff_id"
    type: number
    sql: ${TABLE}.staff_id ;;
  }

  dimension: rental_id {
    label: "rental_id"
    type: number
    sql: ${TABLE}.rental_id ;;
  }

  dimension: amount {
    label: "amount"
    type: number
    sql: ${TABLE}.amount ;;
  }

  dimension_group: payment_date {
    label: "payment_date"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.payment_date ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: revenue {
    label: "Revenue"
    description: "From Power BI measure `Revenue`. Strategy=direct_sum. Direct SUM → type: sum; sql uses ${dimension} (looker-skills). Ref: https://cloud.google.com/looker/docs/reference/param-measure-types DAX: SUM(payment[amount])"
    type: sum
    sql: ${amount} ;;
  }

  measure: count {
    type: count
    drill_fields: [payment_id]
  }

}
