# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: PayType
view: paytype {
  label: "PayType"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.paytype` ;;

  dimension: paytypeid {
    primary_key: yes
    label: "PayTypeID"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: string
    sql: ${TABLE}.PayTypeID ;;
  }

  dimension: paytype {
    label: "PayType"
    type: string
    sql: ${TABLE}.PayType ;;
  }

  measure: count {
    type: count
    drill_fields: [paytypeid]
  }

}
