# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: rentat
view: rentat {
  label: "rentat"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.rentat` ;;

  dimension: rental_id {
    primary_key: yes
    label: "rental_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.rental_id ;;
  }

  dimension_group: rental_date {
    label: "rental_date"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.rental_date ;;
  }

  dimension: inventory_id {
    label: "inventory_id"
    type: number
    sql: ${TABLE}.inventory_id ;;
  }

  dimension: customer_id {
    label: "customer_id"
    type: number
    sql: ${TABLE}.customer_id ;;
  }

  dimension_group: return_date {
    label: "return_date"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.return_date ;;
  }

  dimension: staff_id {
    label: "staff_id"
    type: number
    sql: ${TABLE}.staff_id ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: count {
    type: count
    drill_fields: [rental_id]
  }

}
