# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: SeparationReason
view: separationreason {
  label: "SeparationReason"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.separationreason` ;;

  dimension: separationtypeid {
    primary_key: yes
    label: "SeparationTypeID"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: string
    sql: ${TABLE}.SeparationTypeID ;;
  }

  dimension: separationreason {
    label: "SeparationReason"
    type: string
    sql: ${TABLE}.SeparationReason ;;
  }

  measure: count {
    type: count
    drill_fields: [separationtypeid]
  }

}
