# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: staff
# Standards: looker-open-source/looker-skills + Google Looker docs
# - primary_key first; measures reference ${dimension} where possible
# - measure-of-measures → type: number; ratios use 1.0 * x / NULLIF(y, 0)
# - filters: only on aggregate measure types (not type: number)
view: staff {
  label: "staff"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.staff` ;;

  dimension: staff_id {
    primary_key: yes
    label: "staff_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.staff_id ;;
  }

  dimension: first_name {
    label: "first_name"
    type: string
    sql: ${TABLE}.first_name ;;
  }

  dimension: last_name {
    label: "last_name"
    type: string
    sql: ${TABLE}.last_name ;;
  }

  dimension: address_id {
    label: "address_id"
    type: number
    sql: ${TABLE}.address_id ;;
  }

  dimension: picture {
    label: "picture"
    type: string
    sql: ${TABLE}.picture ;;
  }

  dimension: email {
    label: "email"
    type: string
    sql: ${TABLE}.email ;;
  }

  dimension: store_id {
    label: "store_id"
    type: number
    sql: ${TABLE}.store_id ;;
  }

  dimension: active {
    label: "active"
    type: number
    sql: ${TABLE}.active ;;
  }

  dimension: username {
    label: "username"
    type: string
    sql: ${TABLE}.username ;;
  }

  dimension: password {
    label: "password"
    type: string
    sql: ${TABLE}.password ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: count {
    type: count
    drill_fields: [staff_id]
  }

}
