# GENERATED by phase2/generate_lookml.py — deterministic from Phase 1 inventory
# Source Power BI table: store
# Standards: looker-open-source/looker-skills + Google Looker docs
# - primary_key first; measures reference ${dimension} where possible
# - measure-of-measures → type: number; ratios use 1.0 * x / NULLIF(y, 0)
# - filters: only on aggregate measure types (not type: number)
view: store {
  label: "store"
  sql_table_name: `YOUR_PROJECT.YOUR_DATASET.store` ;;

  dimension: store_id {
    primary_key: yes
    label: "store_id"
    description: "Inferred primary key from Phase 1 inventory naming."
    type: number
    sql: ${TABLE}.store_id ;;
  }

  dimension: manager_staff_id {
    label: "manager_staff_id"
    type: number
    sql: ${TABLE}.manager_staff_id ;;
  }

  dimension: address_id {
    label: "address_id"
    type: number
    sql: ${TABLE}.address_id ;;
  }

  dimension_group: last_update {
    label: "last_update"
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    sql: ${TABLE}.last_update ;;
  }

  measure: count {
    type: count
    drill_fields: [store_id]
  }

}
