#!/usr/bin/env python3
"""Write a simple object-summary PDF from OBJECT_COUNTS / summary text."""
from __future__ import annotations

from pathlib import Path

from fpdf import FPDF

ROOT = Path(__file__).resolve().parent
INV = ROOT / "inventory"
OUT = ROOT / "OBJECT_SUMMARY.pdf"


def latin1(s: str) -> str:
    return (
        str(s)
        .replace("\u2014", "-")
        .replace("\u2013", "-")
        .replace("\u2019", "'")
        .replace("\u2018", "'")
        .replace("\u2192", "->")
        .encode("latin-1", "replace")
        .decode("latin-1")
    )


def write_summary_pdf(
    summary_text: str,
    pbix_name: str,
    out_path: Path | None = None,
) -> Path:
    path = out_path or OUT
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, latin1("PBIX Object Summary"), ln=1)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, latin1(f"Source: {pbix_name}"), ln=1)
    pdf.ln(4)
    pdf.set_font("Courier", "", 10)
    for line in summary_text.splitlines():
        pdf.cell(0, 5, latin1(line), ln=1)
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 9)
    pdf.multi_cell(
        0,
        5,
        latin1(
            "Generated by Phase 1 deterministic extract (6 stages, pbixray). "
            "Full inventory: inventory/OBJECT_INVENTORY.md. "
            "Data model diagram: DATA_MODEL.pdf."
        ),
    )
    pdf.output(str(path))
    return path


if __name__ == "__main__":
    summary = (INV / "OBJECT_SUMMARY.txt").read_text(encoding="utf-8")
    counts_src = "pbix"
    try:
        import json

        counts_src = json.loads((INV / "OBJECT_COUNTS.json").read_text()).get(
            "source_pbix", "pbix"
        )
    except Exception:
        pass
    p = write_summary_pdf(summary, Path(counts_src).name)
    print("Wrote", p)
